version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
    commit-message:
      include: scope
      prefix: bump

  - package-ecosystem: 'npm'
    directory: '/docs'
    schedule:
      interval: 'daily'
    labels:
      - 'kind/dependencies'
    versioning-strategy: 'increase'
    commit-message:
      include: scope
      prefix: bump
