[workspace]
members = [
	"meta/meta-consensus",
	"meta/meta-runtime",
	"meta/meta-node",
	"example/example",
]

[patch.crates-io]
syn = { git = 'https://github.com/dtolnay/syn', tag = '1.0.98', version = '1.0.98' }
