[workspace]
members = [
	"pallets/meta-consensus",
	"runtimes/meta-runtime",
	"nodes/meta-node",
]

[patch.crates-io]
syn = { git = 'https://github.com/dtolnay/syn', tag = '1.0.97', version = '1.0.97' }
