[workspace]
members = [
    "meta/meta-consensus",
    "meta/meta-runtime",
    "meta/meta-node",
]

[patch.crates-io]
syn = { git = 'https://github.com/dtolnay/syn', tag = '1.0.97', version = '1.0.97' }
