[build.environment]
NPM_FLAGS="--version" # prevent Netlify npm install

[build]
publish = "docs/.contented/.preview/out/"
command = "npm install --location=global pnpm && pnpm install --frozen-lockfile && turbo run generate --filter=docs --force"