[package]
name = "meta-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
codec 										= { default-features = false, version = "3.1.5", features = ["derive"], package = "parity-scale-codec" }
scale-info 									= { default-features = false, version = "2.1.2", features = ["derive"] }
serde 										= { default-features = false, version = "1.0.141", features = ["derive"], optional = true }

# Substrate packages
frame-executive 							= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
frame-support 								= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
frame-system 								= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
frame-system-rpc-runtime-api 				= { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.25'  }

pallet-balances 							= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
pallet-sudo 								= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
pallet-timestamp 							= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
pallet-transaction-payment 					= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
pallet-transaction-payment-rpc-runtime-api 	= { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.25'  }

sp-api 										= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-block-builder 							= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-core 									= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-inherents 								= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-io 										= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-offchain 								= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-runtime 									= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-session 									= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-std 										= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-transaction-pool 						= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }
sp-version 									= { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.25' }

# frontier packages
fp-rpc										= { default-features = false, git = 'https://github.com/paritytech/frontier.git', branch = 'polkadot-v0.9.25' }
fp-self-contained 							= { default-features = false, git = 'https://github.com/paritytech/frontier.git', branch = 'polkadot-v0.9.25' }

pallet-base-fee 							= { default-features = false, git = "https://github.com/paritytech/frontier.git", branch = 'polkadot-v0.9.25' }
pallet-dynamic-fee 							= { default-features = false, git = "https://github.com/paritytech/frontier.git", branch = 'polkadot-v0.9.25' }
pallet-ethereum 							= { default-features = false, git = "https://github.com/paritytech/frontier.git", branch = 'polkadot-v0.9.25' }
pallet-evm 									= { default-features = false, git = "https://github.com/paritytech/frontier.git", branch = 'polkadot-v0.9.25' }

[build-dependencies]
substrate-wasm-builder 						= { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.25' }

[features]
default = ["std"]
std = [
	"serde",
	# Parity
	"codec/std",
	"scale-info/std",

	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",

	"pallet-balances/std",
	"pallet-base-fee/std",
	"pallet-dynamic-fee/std",
	"pallet-ethereum/std",
	"pallet-evm/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",

	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	"fp-rpc/std",
	"fp-self-contained/std",
]
