[package]
name = "meta-defichain-rpc-runtime-api"
version = "0.1.0"
edition = "2021"

[dependencies]
sp-api 		              = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.27" }

[features]
default = ["std"]
std = [
    "sp-api/std",
]