[package]
name = "meta-node"
version = "0.1.0"
edition = "2021"

[dependencies]
meta-core = { path = "core", default-features = false }

[features]
default = ["birthday-native", "meta-native"]

birthday-native = ["meta-core/birthday-native"]
meta-native = ["meta-core/meta-native"]