name: OSS Governance

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  Labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@12623606c1cb561e9fff26c8f275563a3a39ba8f # tag=v2.0.0
        with:
          github-token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          config-path: .github/labeler.yml
