name: CD

on:
  release:
    types: [published]
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    name: Publish
    runs-on: ubuntu-latest
    environment: Release Docker
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Cache
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3.0.10
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true
          override: true

      - name: Cargo build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # tag=v1.0.3
        with:
          command: build
          args: --release --all

      - name: Save binary
        run: |
          mkdir -p build
          cp target/release/meta-node build/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # tag=v2.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tags
        uses: actions/github-script@100527700e8b29ca817ac0e0dfbfc5e8ff38edda # tag=v6.3.2
        id: tags
        with:
          script: |
            const prefix = 'ghcr.io/defich/metachain'
            if (context.eventName === 'release') {
                const semver = context.payload?.release?.tag_name
                if (semver.match(/^v[0-9]+\.[0-9]+\.[0-9]+$/) === null) {
                    throw new Error(`Release Violation: Provided version '${semver}' is not valid semver.`)
                }
                return `${prefix}:latest,${prefix}:${semver.replace('v','')}`
            }
              
            if (context.eventName === 'push' && context.ref === 'refs/heads/main') {
                return `${prefix}:main,${prefix}:${context.sha}`
            }
              
            if (context.eventName === 'pull_request') {
                return `${prefix}:${context.payload.number},${prefix}:${context.sha}`
            }

          result-encoding: string

      - name: Support multi-platform
        run: |
          sed -i 's/FROM /FROM --platform=$BUILDPLATFORM /g' ./Dockerfile

      - name: Build & Publish
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3.1.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ steps.tags.outputs.result }}
          cache-from: type=registry,ref=ghcr.io/defich/metachain:buildcache
          cache-to: type=registry,ref=ghcr.io/defich/metachain:buildcache,mode=max

      - name: Post Report
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56 # tag=v2.3.0
        with:
          header: release
          message: |
            Docker image for defich/metachain is ready!

            Built with commit ${{ github.sha }}

            - `docker pull ghcr.io/defich/metachain:${{ github.sha }}`
            - `docker pull ghcr.io/defich/metachain:pr-${{ github.event.number }}`
